// All countries
// length 252
var countries = [
    { "name": "Afghanistan", "continent": "Asia", "capital": "Kabul" },
    { "name": "Aland Islands", "continent": "Europe", "capital": "Mariehamn" },
    { "name": "Albania", "continent": "Europe", "capital": "Tirana" },
    { "name": "Algeria", "continent": "Africa", "capital": "Algiers" },
    { "name": "American Samoa", "continent": "Oceania", "capital": "Pago Pago" },
    { "name": "Andorra", "continent": "Europe", "capital": "Andorra la Vella" },
    { "name": "Angola", "continent": "Africa", "capital": "Luanda" },
    { "name": "Anguilla", "continent": "North America", "capital": "The Valley" },
    { "name": "Antarctica", "continent": "Antarctica", "capital": "Antarctica" },
    { "name": "Antigua and Barbuda", "continent": "North America", "capital": "St. John's" },
    { "name": "Argentina", "continent": "South America", "capital": "Buenos Aires" },
    { "name": "Armenia", "continent": "Asia", "capital": "Yerevan" },
    { "name": "Aruba", "continent": "North America", "capital": "Oranjestad" },
    { "name": "Australia", "continent": "Oceania", "capital": "Canberra" },
    { "name": "Austria", "continent": "Europe", "capital": "Vienna" },
    { "name": "Azerbaijan", "continent": "Asia", "capital": "Baku" },
    { "name": "Bahamas", "continent": "North America", "capital": "Nassau" },
    { "name": "Bahrain", "continent": "Asia", "capital": "Manama" },
    { "name": "Bangladesh", "continent": "Asia", "capital": "Dhaka" },
    { "name": "Barbados", "continent": "North America", "capital": "Bridgetown" },
    { "name": "Belarus", "continent": "Europe", "capital": "Minsk" },
    { "name": "Belgium", "continent": "Europe", "capital": "Brussels" },
    { "name": "Belize", "continent": "North America", "capital": "Belmopan" },
    { "name": "Benin", "continent": "Africa", "capital": "Porto-Novo" },
    { "name": "Bermuda", "continent": "North America", "capital": "Hamilton" },
    { "name": "Bhutan", "continent": "Asia", "capital": "Thimphu" },
    { "name": "Bolivia", "continent": "South America", "capital": "Sucre" },
    { "name": "Bonaire, Sint Eustatius and Saba", "continent": "North America", "capital": "Kralendijk" },
    { "name": "Bosnia and Herzegovina", "continent": "Europe", "capital": "Sarajevo" },
    { "name": "Botswana", "continent": "Africa", "capital": "Gaborone" },
    { "name": "Bouvet Island", "continent": "Antarctica", "capital": "" },
    { "name": "Brazil", "continent": "South America", "capital": "Brasilia" },
    { "name": "British Indian Ocean Territory", "continent": "Asia", "capital": "Diego Garcia" },
    { "name": "Brunei Darussalam", "continent": "Asia", "capital": "Bandar Seri Begawan" },
    { "name": "Bulgaria", "continent": "Europe", "capital": "Sofia" },
    { "name": "Burkina Faso", "continent": "Africa", "capital": "Ouagadougou" },
    { "name": "Burundi", "continent": "Africa", "capital": "Bujumbura" },
    { "name": "Cambodia", "continent": "Asia", "capital": "Phnom Penh" },
    { "name": "Cameroon", "continent": "Africa", "capital": "Yaounde" },
    { "name": "Canada", "continent": "North America", "capital": "Ottawa" },
    { "name": "Cape Verde", "continent": "Africa", "capital": "Praia" },
    { "name": "Cayman Islands", "continent": "North America", "capital": "George Town" },
    { "name": "Central African Republic", "continent": "Africa", "capital": "Bangui" },
    { "name": "Chad", "continent": "Africa", "capital": "N'Djamena" },
    { "name": "Chile", "continent": "South America", "capital": "Santiago" },
    { "name": "China", "continent": "Asia", "capital": "Beijing" },
    { "name": "Christmas Island", "continent": "Asia", "capital": "Flying Fish Cove" },
    { "name": "Cocos (Keeling) Islands", "continent": "Asia", "capital": "West Island" },
    { "name": "Colombia", "continent": "South America", "capital": "Bogota" },
    { "name": "Comoros", "continent": "Africa", "capital": "Moroni" },
    { "name": "Congo", "continent": "Africa", "capital": "Brazzaville" },
    { "name": "Congo, Democratic Republic of the Congo", "continent": "Africa", "capital": "Kinshasa" },
    { "name": "Cook Islands", "continent": "Oceania", "capital": "Avarua" },
    { "name": "Costa Rica", "continent": "North America", "capital": "San Jose" },
    { "name": "Cote D'Ivoire", "continent": "Africa", "capital": "Yamoussoukro" },
    { "name": "Croatia", "continent": "Europe", "capital": "Zagreb" },
    { "name": "Cuba", "continent": "North America", "capital": "Havana" },
    { "name": "Curacao", "continent": "North America", "capital": "Willemstad" },
    { "name": "Cyprus", "continent": "Asia", "capital": "Nicosia" },
    { "name": "Czech Republic", "continent": "Europe", "capital": "Prague" },
    { "name": "Denmark", "continent": "Europe", "capital": "Copenhagen" },
    { "name": "Djibouti", "continent": "Africa", "capital": "Djibouti" },
    { "name": "Dominica", "continent": "North America", "capital": "Roseau" },
    { "name": "Dominican Republic", "continent": "North America", "capital": "Santo Domingo" },
    { "name": "Ecuador", "continent": "South America", "capital": "Quito" },
    { "name": "Egypt", "continent": "Africa", "capital": "Cairo" },
    { "name": "El Salvador", "continent": "North America", "capital": "San Salvador" },
    { "name": "Equatorial Guinea", "continent": "Africa", "capital": "Malabo" },
    { "name": "Eritrea", "continent": "Africa", "capital": "Asmara" },
    { "name": "Estonia", "continent": "Europe", "capital": "Tallinn" },
    { "name": "Ethiopia", "continent": "Africa", "capital": "Addis Ababa" },
    { "name": "Falkland Islands (Malvinas)", "continent": "South America", "capital": "Stanley" },
    { "name": "Faroe Islands", "continent": "Europe", "capital": "Torshavn" },
    { "name": "Fiji", "continent": "Oceania", "capital": "Suva" },
    { "name": "Finland", "continent": "Europe", "capital": "Helsinki" },
    { "name": "France", "continent": "Europe", "capital": "Paris" },
    { "name": "French Guiana", "continent": "South America", "capital": "Cayenne" },
    { "name": "French Polynesia", "continent": "Oceania", "capital": "Papeete" },
    { "name": "French Southern Territories", "continent": "Antarctica", "capital": "Port-aux-Francais" },
    { "name": "Gabon", "continent": "Africa", "capital": "Libreville" },
    { "name": "Gambia", "continent": "Africa", "capital": "Banjul" },
    { "name": "Georgia", "continent": "Asia", "capital": "Tbilisi" },
    { "name": "Germany", "continent": "Europe", "capital": "Berlin" },
    { "name": "Ghana", "continent": "Africa", "capital": "Accra" },
    { "name": "Gibraltar", "continent": "Europe", "capital": "Gibraltar" },
    { "name": "Greece", "continent": "Europe", "capital": "Athens" },
    { "name": "Greenland", "continent": "North America", "capital": "Nuuk" },
    { "name": "Grenada", "continent": "North America", "capital": "St. George's" },
    { "name": "Guadeloupe", "continent": "North America", "capital": "Basse-Terre" },
    { "name": "Guam", "continent": "Oceania", "capital": "Hagatna" },
    { "name": "Guatemala", "continent": "North America", "capital": "Guatemala City" },
    { "name": "Guernsey", "continent": "Europe", "capital": "St Peter Port" },
    { "name": "Guinea", "continent": "Africa", "capital": "Conakry" },
    { "name": "Guinea-Bissau", "continent": "Africa", "capital": "Bissau" },
    { "name": "Guyana", "continent": "South America", "capital": "Georgetown" },
    { "name": "Haiti", "continent": "North America", "capital": "Port-au-Prince" },
    { "name": "Heard Island and Mcdonald Islands", "continent": "Antarctica", "capital": "" },
    { "name": "Holy See (Vatican City State)", "continent": "Europe", "capital": "Vatican City" },
    { "name": "Honduras", "continent": "North America", "capital": "Tegucigalpa" },
    { "name": "Hong Kong", "continent": "Asia", "capital": "Hong Kong" },
    { "name": "Hungary", "continent": "Europe", "capital": "Budapest" },
    { "name": "Iceland", "continent": "Europe", "capital": "Reykjavik" },
    { "name": "India", "continent": "Asia", "capital": "New Delhi" },
    { "name": "Indonesia", "continent": "Asia", "capital": "Jakarta" },
    { "name": "Iran, Islamic Republic of", "continent": "Asia", "capital": "Tehran" },
    { "name": "Iraq", "continent": "Asia", "capital": "Baghdad" },
    { "name": "Ireland", "continent": "Europe", "capital": "Dublin" },
    { "name": "Isle of Man", "continent": "Europe", "capital": "Douglas, Isle of Man" },
    { "name": "Israel", "continent": "Asia", "capital": "Jerusalem" },
    { "name": "Italy", "continent": "Europe", "capital": "Rome" },
    { "name": "Jamaica", "continent": "North America", "capital": "Kingston" },
    { "name": "Japan", "continent": "Asia", "capital": "Tokyo" },
    { "name": "Jersey", "continent": "Europe", "capital": "Saint Helier" },
    { "name": "Jordan", "continent": "Asia", "capital": "Amman" },
    { "name": "Kazakhstan", "continent": "Asia", "capital": "Astana" },
    { "name": "Kenya", "continent": "Africa", "capital": "Nairobi" },
    { "name": "Kiribati", "continent": "Oceania", "capital": "Tarawa" },
    { "name": "Korea, Democratic People's Republic of", "continent": "Asia", "capital": "Pyongyang" },
    { "name": "Korea, Republic of", "continent": "Asia", "capital": "Seoul" },
    { "name": "Kosovo", "continent": "Europe", "capital": "Pristina" },
    { "name": "Kuwait", "continent": "Asia", "capital": "Kuwait City" },
    { "name": "Kyrgyzstan", "continent": "Asia", "capital": "Bishkek" },
    { "name": "Lao People's Democratic Republic", "continent": "Asia", "capital": "Vientiane" },
    { "name": "Latvia", "continent": "Europe", "capital": "Riga" },
    { "name": "Lebanon", "continent": "Asia", "capital": "Beirut" },
    { "name": "Lesotho", "continent": "Africa", "capital": "Maseru" },
    { "name": "Liberia", "continent": "Africa", "capital": "Monrovia" },
    { "name": "Libyan Arab Jamahiriya", "continent": "Africa", "capital": "Tripolis" },
    { "name": "Liechtenstein", "continent": "Europe", "capital": "Vaduz" },
    { "name": "Lithuania", "continent": "Europe", "capital": "Vilnius" },
    { "name": "Luxembourg", "continent": "Europe", "capital": "Luxembourg" },
    { "name": "Macao", "continent": "Asia", "capital": "Macao" },
    { "name": "Macedonia, the Former Yugoslav Republic of", "continent": "Europe", "capital": "Skopje" },
    { "name": "Madagascar", "continent": "Africa", "capital": "Antananarivo" },
    { "name": "Malawi", "continent": "Africa", "capital": "Lilongwe" },
    { "name": "Malaysia", "continent": "Asia", "capital": "Kuala Lumpur" },
    { "name": "Maldives", "continent": "Asia", "capital": "Male" },
    { "name": "Mali", "continent": "Africa", "capital": "Bamako" },
    { "name": "Malta", "continent": "Europe", "capital": "Valletta" },
    { "name": "Marshall Islands", "continent": "Oceania", "capital": "Majuro" },
    { "name": "Martinique", "continent": "North America", "capital": "Fort-de-France" },
    { "name": "Mauritania", "continent": "Africa", "capital": "Nouakchott" },
    { "name": "Mauritius", "continent": "Africa", "capital": "Port Louis" },
    { "name": "Mayotte", "continent": "Africa", "capital": "Mamoudzou" },
    { "name": "Mexico", "continent": "North America", "capital": "Mexico City" },
    { "name": "Micronesia, Federated States of", "continent": "Oceania", "capital": "Palikir" },
    { "name": "Moldova, Republic of", "continent": "Europe", "capital": "Chisinau" },
    { "name": "Monaco", "continent": "Europe", "capital": "Monaco" },
    { "name": "Mongolia", "continent": "Asia", "capital": "Ulan Bator" },
    { "name": "Montenegro", "continent": "Europe", "capital": "Podgorica" },
    { "name": "Montserrat", "continent": "North America", "capital": "Plymouth" },
    { "name": "Morocco", "continent": "Africa", "capital": "Rabat" },
    { "name": "Mozambique", "continent": "Africa", "capital": "Maputo" },
    { "name": "Myanmar", "continent": "Asia", "capital": "Nay Pyi Taw" },
    { "name": "Namibia", "continent": "Africa", "capital": "Windhoek" },
    { "name": "Nauru", "continent": "Oceania", "capital": "Yaren" },
    { "name": "Nepal", "continent": "Asia", "capital": "Kathmandu" },
    { "name": "Netherlands", "continent": "Europe", "capital": "Amsterdam" },
    { "name": "Netherlands Antilles", "continent": "North America", "capital": "Willemstad" },
    { "name": "New Caledonia", "continent": "Oceania", "capital": "Noumea" },
    { "name": "New Zealand", "continent": "Oceania", "capital": "Wellington" },
    { "name": "Nicaragua", "continent": "North America", "capital": "Managua" },
    { "name": "Niger", "continent": "Africa", "capital": "Niamey" },
    { "name": "Nigeria", "continent": "Africa", "capital": "Abuja" },
    { "name": "Niue", "continent": "Oceania", "capital": "Alofi" },
    { "name": "Norfolk Island", "continent": "Oceania", "capital": "Kingston" },
    { "name": "Northern Mariana Islands", "continent": "Oceania", "capital": "Saipan" },
    { "name": "Norway", "continent": "Europe", "capital": "Oslo" },
    { "name": "Oman", "continent": "Asia", "capital": "Muscat" },
    { "name": "Pakistan", "continent": "Asia", "capital": "Islamabad" },
    { "name": "Palau", "continent": "Oceania", "capital": "Melekeok" },
    { "name": "Palestinian Territory, Occupied", "continent": "Asia", "capital": "East Jerusalem" },
    { "name": "Panama", "continent": "North America", "capital": "Panama City" },
    { "name": "Papua New Guinea", "continent": "Oceania", "capital": "Port Moresby" },
    { "name": "Paraguay", "continent": "South America", "capital": "Asuncion" },
    { "name": "Peru", "continent": "South America", "capital": "Lima" },
    { "name": "Philippines", "continent": "Asia", "capital": "Manila" },
    { "name": "Pitcairn", "continent": "Oceania", "capital": "Adamstown" },
    { "name": "Poland", "continent": "Europe", "capital": "Warsaw" },
    { "name": "Portugal", "continent": "Europe", "capital": "Lisbon" },
    { "name": "Puerto Rico", "continent": "North America", "capital": "San Juan" },
    { "name": "Qatar", "continent": "Asia", "capital": "Doha" },
    { "name": "Reunion", "continent": "Africa", "capital": "Saint-Denis" },
    { "name": "Romania", "continent": "Europe", "capital": "Bucharest" },
    { "name": "Russian Federation", "continent": "Asia", "capital": "Moscow" },
    { "name": "Rwanda", "continent": "Africa", "capital": "Kigali" },
    { "name": "Saint Barthelemy", "continent": "North America", "capital": "Gustavia" },
    { "name": "Saint Helena", "continent": "Africa", "capital": "Jamestown" },
    { "name": "Saint Kitts and Nevis", "continent": "North America", "capital": "Basseterre" },
    { "name": "Saint Lucia", "continent": "North America", "capital": "Castries" },
    { "name": "Saint Martin", "continent": "North America", "capital": "Marigot" },
    { "name": "Saint Pierre and Miquelon", "continent": "North America", "capital": "Saint-Pierre" },
    { "name": "Saint Vincent and the Grenadines", "continent": "North America", "capital": "Kingstown" },
    { "name": "Samoa", "continent": "Oceania", "capital": "Apia" },
    { "name": "San Marino", "continent": "Europe", "capital": "San Marino" },
    { "name": "Sao Tome and Principe", "continent": "Africa", "capital": "Sao Tome" },
    { "name": "Saudi Arabia", "continent": "Asia", "capital": "Riyadh" },
    { "name": "Senegal", "continent": "Africa", "capital": "Dakar" },
    { "name": "Serbia", "continent": "Europe", "capital": "Belgrade" },
    { "name": "Serbia and Montenegro", "continent": "Europe", "capital": "Belgrade" },
    { "name": "Seychelles", "continent": "Africa", "capital": "Victoria" },
    { "name": "Sierra Leone", "continent": "Africa", "capital": "Freetown" },
    { "name": "Singapore", "continent": "Asia", "capital": "Singapur" },
    { "name": "Sint Maarten", "continent": "North America", "capital": "Philipsburg" },
    { "name": "Slovakia", "continent": "Europe", "capital": "Bratislava" },
    { "name": "Slovenia", "continent": "Europe", "capital": "Ljubljana" },
    { "name": "Solomon Islands", "continent": "Oceania", "capital": "Honiara" },
    { "name": "Somalia", "continent": "Africa", "capital": "Mogadishu" },
    { "name": "South Africa", "continent": "Africa", "capital": "Pretoria" },
    { "name": "South Georgia and the South Sandwich Islands", "continent": "Antarctica", "capital": "Grytviken" },
    { "name": "South Sudan", "continent": "Africa", "capital": "Juba" },
    { "name": "Spain", "continent": "Europe", "capital": "Madrid" },
    { "name": "Sri Lanka", "continent": "Asia", "capital": "Colombo" },
    { "name": "Sudan", "continent": "Africa", "capital": "Khartoum" },
    { "name": "Suriname", "continent": "South America", "capital": "Paramaribo" },
    { "name": "Svalbard and Jan Mayen", "continent": "Europe", "capital": "Longyearbyen" },
    { "name": "Swaziland", "continent": "Africa", "capital": "Mbabane" },
    { "name": "Sweden", "continent": "Europe", "capital": "Stockholm" },
    { "name": "Switzerland", "continent": "Europe", "capital": "Berne" },
    { "name": "Syrian Arab Republic", "continent": "Asia", "capital": "Damascus" },
    { "name": "Taiwan, Province of China", "continent": "Asia", "capital": "Taipei" },
    { "name": "Tajikistan", "continent": "Asia", "capital": "Dushanbe" },
    { "name": "Tanzania, United Republic of", "continent": "Africa", "capital": "Dodoma" },
    { "name": "Thailand", "continent": "Asia", "capital": "Bangkok" },
    { "name": "Timor-Leste", "continent": "Asia", "capital": "Dili" },
    { "name": "Togo", "continent": "Africa", "capital": "Lome" },
    { "name": "Tokelau", "continent": "Oceania", "capital": "" },
    { "name": "Tonga", "continent": "Oceania", "capital": "Nuku'alofa" },
    { "name": "Trinidad and Tobago", "continent": "North America", "capital": "Port of Spain" },
    { "name": "Tunisia", "continent": "Africa", "capital": "Tunis" },
    { "name": "Turkey", "continent": "Europe", "capital": "Ankara" },
    { "name": "Turkmenistan", "continent": "Asia", "capital": "Ashgabat" },
    { "name": "Turks and Caicos Islands", "continent": "North America", "capital": "Cockburn Town" },
    { "name": "Tuvalu", "continent": "Oceania", "capital": "Funafuti" },
    { "name": "Uganda", "continent": "Africa", "capital": "Kampala" },
    { "name": "Ukraine", "continent": "Europe", "capital": "Kiev" },
    { "name": "United Arab Emirates", "continent": "Asia", "capital": "Abu Dhabi" },
    { "name": "United Kingdom", "continent": "Europe", "capital": "London" },
    { "name": "United States", "continent": "North America", "capital": "Washington" },
    { "name": "United States Minor Outlying Islands", "continent": "North America", "capital": "" },
    { "name": "Uruguay", "continent": "South America", "capital": "Montevideo" },
    { "name": "Uzbekistan", "continent": "Asia", "capital": "Tashkent" },
    { "name": "Vanuatu", "continent": "Oceania", "capital": "Port Vila" },
    { "name": "Venezuela", "continent": "South America", "capital": "Caracas" },
    { "name": "Viet Nam", "continent": "Asia", "capital": "Hanoi" },
    { "name": "Virgin Islands, British", "continent": "North America", "capital": "Road Town" },
    { "name": "Virgin Islands, U.s.", "continent": "North America", "capital": "Charlotte Amalie" },
    { "name": "Wallis and Futuna", "continent": "Oceania", "capital": "Mata Utu" },
    { "name": "Western Sahara", "continent": "Africa", "capital": "El-Aaiun" },
    { "name": "Yemen", "continent": "Asia", "capital": "Sanaa" },
    { "name": "Zambia", "continent": "Africa", "capital": "Lusaka" },
    { "name": "Zimbabwe", "continent": "Africa", "capital": "Harare" }
];